[profile.default]
#solc = "0.8.20"
auto_detect_solc = true
src = 'src'
out = 'out'
libs = ['lib']
no_match_path = "*/integration/*"
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
optimizer_runs = 1000000
optimizer = true

[profile.integration]
no_match_path = ""
match_path = "*/integration/*"

[profile.lite.optimizer_details.yulDetails]
stackAllocation = true
optimizerSteps = 'xca'
